#model:
input_size: 6
embedding_size: 8
hidden_size: 64
number_output_size: 13
speed_output_size: 3
t_predict: 4
temporal_length: 16

# train
batch_size: 500
num_epochs: 50
show_every: 200
learning_rate: 0.003
decay_rate: 0.95
lambda_param: 0.0005
use_cuda: true
flow_loss_weight: 1
output_loss_weight: 1
speed_loss_weight: 1
grad_clip: 10
sample_rate: 0
sample_decay: 1
use_mask: true
use_simerror: true
gamma: 0.5
num_workers: 1
rand_range: 0.2

# data
seg:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
use_speed: true
sim_step: 0.1
delta_T: 10
cycle: 100
green_pass: 52
n_units: 7

model_prefix: multi_dimension

prefix:
  - unit
  - change

test_prefix:
  - test

mask:
  - 0.5
  - 1
  - 2
  - 3
  - 4
  - 20
  - 24
  - 28
  - 32
  - 36
  - 40
  - 44
  - 48

#拓扑结构写死在data.py内部