# test
batch_size: 100
use_epoch: 49
model_prefix: with_mask
t_predict: 4
temporal_length: 204
use_cuda: true

# eva
hidden_size: 64
input_size: 3
lane_gate_size: 4
output_hidden_size: 16
eva_prefix: 
  - 2000_nosignal
spatial_length: 40

#data
sim_step: 0.1
delta_T: 10
cycle: 100
green_pass: 52