#model:
input_size: 3
embedding_size: 8
hidden_size: 64
output_hidden_size: 16
output_size: 1
t_predict: 8
temporal_length: 16

encoder_hidden: 64
decoder_input: 64
decoder_hidden: 128

n_head: 4

# train
batch_size: 500
num_epochs: 20
show_every: 200
learning_rate: 0.003
decay_rate: 0.95
lambda_param: 0.0005
use_cuda: true
output_loss_weight: 1
flow_loss_weight: 1
speed_loss_weight: 1
seg_loss_weight: 1
grad_clip: 10
sample_rate: 0
sample_decay: 0.1
use_mask: false
use_simerror: true
gamma: 0.5
num_workers: 1
rand_range: 0.1

# data
seg:
  - 1
use_speed: false
sim_step: 0.1
delta_T: 10
cycle: 100
green_pass: 52
n_units: 7

log_path: second_phase
model_path: multi_dimension
use_epoch: 47

prefix:
  - I-80_1_
  - I-80_2_

test_prefix:
  - I-80_3_
