# test
batch_size: 100
use_epoch: 49
model_prefix: all_flow
t_predict: 4
temporal_length: 80
time: 2000
use_cuda: true
rand_range: 0.2

# eva
hidden_size: 64
output_hidden_size: 16
input_size: 6
lane_gate_size: 4
output_size: 4
eva_prefix: test
spatial_length: 40
current_time: 0
n_units: 7

#data
sim_step: 0.1
delta_T: 10
cycle: 100
green_pass: 52
seg: 6
use_speed: true