# test
batch_size: 100
use_epoch: 4
model_prefix: disc_samll_weight
t_predict: 4
temporal_length: 204
time: 0
use_cuda: true
rand_range: 0.2

# eva
hidden_size: 64
input_size: 3
lane_gate_size: 4
output_size: 13
eva_prefix: 
  - test1
  - test2
  - test3
  - test4
spatial_length: 40
current_time: 0
topology_index: 
  - 0
  - 1
  - 0
  - 1
n_units: 7

#data
sim_step: 0.1
delta_T: 10
cycle: 100
green_pass: 52
seg: 2