# test
batch_size: 100
use_epoch: 49
model_prefix: no_ad
t_predict: 8
temporal_length: 370
time: 0
use_cuda: true
rand_range: 0.2

encoder_hidden: 64
decoder_input: 64
decoder_hidden: 128
n_head: 4

# eva
hidden_size: 64
output_hidden_size: 16
input_size: 3
lane_gate_size: 4
output_size: 1
eva_prefix: test
spatial_length: 40
current_time: 0
n_units: 7

#data
sim_step: 0.1
delta_T: 10
cycle: 100
green_pass: 52
seg: 4
use_speed: false