# test
batch_size: 100
use_epoch: 49
model_prefix: 6_lane_baseline
t_predict: 4
temporal_length: 370
time: 0
use_cuda: true
rand_range: 0.2

speed_input_size: 3
speed_output_size: 3
speed_encoder_hidden: 64
number_input_size: 3
number_output_size: 1
number_encoder_hidden: 64
decoder_hidden: 64

# eva
hidden_size: 64
output_hidden_size: 16
input_size: 3
lane_gate_size: 4
output_size: 1
eva_prefix: change
spatial_length: 40
current_time: 0
n_units: 7

#data
sim_step: 0.1
delta_T: 10
cycle: 100
green_pass: 52
seg: 2
use_speed: false