#model:
input_size: 6
embedding_size: 8
hidden_size: 64
output_size: 2
t_predict: 8
temporal_length: 16
n_head: 4

# train
batch_size: 500
num_epochs: 50
show_every: 200
learning_rate: 0.003
decay_rate: 0.95
lambda_param: 0.0005
use_cuda: true
output_loss_weight: 1
flow_loss_weight: 1
seg_loss_weight: 1
grad_clip: 10
sample_rate: 1
sample_decay: 0.1
use_simerror: true
gamma: 0.5
num_workers: 1

# data
seg:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
sim_step: 0.1
delta_T: 10

model_prefix: multi_dimension

prefix:
  - base
  - change

test_prefix:
  - change
